# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: nox
        name: nox
        entry: uv run nox -s lint
        language: system
        pass_filenames: false
        always_run: true
